# Matrix Bridge Configuration
serverURL: "http://localhost:8008"
publicServerURL: "http://localhost:8008"
matrixDomain: "localhost" # Domain of the matrix server, the end part on userIDs

appservicePort: 9000

db:
  type: "leveldb" # Must be one of the following: leveldb, mongo
  directory: "/srv/matrix-bridge/db"
  compression: true # Must be true or false
  cacheSize: 100 # in megabytes
#db:
#  type: "mongodb"
#  url: "mongo://localhost"
#  database: "exampleDb"